volumes:
  mariadb_data:

services:
  apache:
    container_name: apache
    build:
      context: .
      dockerfile_inline: |
        FROM php:8.5-apache
        RUN docker-php-ext-install -j$(nproc) pdo_mysql
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
    command:
      - /bin/sh
      - -lc
      - |
        cat > /etc/apache2/sites-available/000-default.conf <<"EOF"
        <VirtualHost *:80>
            DocumentRoot /var/www/html
            ErrorLog $${APACHE_LOG_DIR}/error.log
            CustomLog $${APACHE_LOG_DIR}/access.log combined

            <Directory /var/www/html>
                Options +Indexes
            </Directory>
        </VirtualHost>
        EOF
        exec apache2-foreground

  mailpit:
    container_name: mailpit
    image: axllent/mailpit:v1.30
    ports:
      - 1025:1025
      - 8025:8025

  mariadb:
    container_name: mariadb
    image: mariadb:12
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=yes
      - MARIADB_USER=username
      - MARIADB_PASSWORD=password
      - MARIADB_DATABASE=my_database
    ports:
      - 3306:3306
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:5
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
      - PMA_DATABASE=my_database
    ports:
      - 9090:80
